# 项目名
name: github pages

# 只有在master分支上发生push事件时触发
on:
  push:
    branches:
      - master # default branch

# 工作流
jobs:
  deploy:
    runs-on: ubuntu-latest # 运行环境
    steps:
      # 拉代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 下载node
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      # 安装依赖
      - run: npm install --global pnpm
      - run: pnpm install
      # 打包文档
      - run: pnpm run docs:build

      # 部署到github
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs-dist
